### ISSUE TITLE
Lowest latency term?

### ISSUE THREAD

**Issue by dm17** [anarcat/terms-benchmarks#5]
It seems st has an fps setting:
https://lwn.net/Articles/752894/

I'm not sure which other terminal emulators have similar optimal settings - but isn't st the lowest latency when taking this into account?

**Comment by dm17** [comment]
Also, I wonder if something like this can be done in terminal emulators:
https://www.testufo.com/

It is pretty standard for evaluating latency issues. It would be a sweet addition for evaluating term performance.

**Comment by anarcat** [comment]
> It seems st has an fps setting[...]

I'm sure there are various ways to optimize all those emulators by patching the source code in various ways. I only concerned myself with out of the box behavior.

> Also, I wonder if something like this can be done in terminal emulators:
https://www.testufo.com/
>
> It is pretty standard for evaluating latency issues. It would be a sweet addition for evaluating term performance.

What is even going on here... All I see are flying "UFOs" and a big red warning that says:

> **VSYNC is not available on the Linux platform.**

Not sure what to make of this site...

... or this issue, actually. :) What do you want me to do here exactly? The results I have from those tests are in [this article](https://lwn.net/Articles/751763/) and show xterm to be the winner in terms of latency, followed closely by mlterm. Even with the patches to st you suggested, it's still above the 3ms mark, 1ms slower than xterm on average. And that's kind of cheating because you're changing the shell...

Feel free to reopen if there's any specific question you want me to answer!

**Comment by dm17** [comment]
> > It seems st has an fps setting[...]
> 
> I'm sure there are various ways to optimize all those emulators by patching the source code in various ways. I only concerned myself with out of the box behavior.

I think it is pretty reasonable to re-test st with the FPS setting all the way up. I didn't realize it had such a setting until I saw that commend in your article. Of course I'd like to know if the other terminal emulators have such a setting, but it is a setting & not a "patch," right? It would be good to know the latency of st with this setting all the way up, if you're willing :)

> > Also, I wonder if something like this can be done in terminal emulators:
> > https://www.testufo.com/
> > It is pretty standard for evaluating latency issues. It would be a sweet addition for evaluating term performance.
> 
> What is even going on here... All I see are flying "UFOs" and a big red warning that says:

Ya, maybe it is javascript only, so don't know if that can be made to work in a terminal emulator. the "VSYNC not available" error is just detecting that you're using Linux and then displaying that. The explanation for that is here, even though it isn't necessarily true for your specific setup:
https://forums.blurbusters.com/viewtopic.php?f=19&t=3842

More info about what it tests & how on their website.

> > **VSYNC is not available on the Linux platform.**
> 
> Not sure what to make of this site...
> 
> ... or this issue, actually. :) What do you want me to do here exactly? The results I have from those tests are in [this article](https://lwn.net/Articles/751763/) and show xterm to be the winner in terms of latency, followed closely by mlterm. Even with the patches to st you suggested, it's still above the 3ms mark, 1ms slower than xterm on average. And that's kind of cheating because you're changing the shell...

Ah, so xterm would be below 3ms with dash, then? Cool.

> 
> Feel free to reopen if there's any specific question you want me to answer!

Thanks!

**Comment by anarcat** [comment]
> I think it is pretty reasonable to re-test st with the FPS setting all the way up. I didn't realize it had such a setting until I saw that commend in your article.

It's not reasonable to expect *me* to rerun the entire test suite I designed to write those two articles every time someone comes up with a new idea like this one. :p The entire reason I published this online is so that *others* (as in: not me) could reproduce those results. You are entirely free to clone this repository and run those tests yourself: that's why I published this repo.

You need to understand that, in order to do what you're asking me I would need to:

 1. redeploy a Fedora install
 2. recompile Alacritty (because no, they're still not packaged in Debian)
 3. install all those packages in Debian (and probably missing some that were removed from Debian)
 4. treat st as another special snowflake (like Alacritty) and download and audit and compile and tweak the source code
 5. *finally*, run the latency test

What will happen at that point is probably that someone will (rightly) point out that I (again) forgot their favorite terminal emulator (again). Tilix and Kitty are in popular demand, but I wouldn't be surprised to learn about a completely new one in the process as well.

The last time I did this is in April, here: https://github.com/jwilm/alacritty/issues/673#issuecomment-481082227 What happened next is that *you* commented to see if the benchmark was done "with the latest code". I honestly don't quite understand what you expect from this universe, but I don't think it's fair to expect everyone will constantly rerun those benchmarks everywhere all the time. Those are all done manually, and they are not part of a formal test suite.

They also need to be taken with a grain of salt.

> Of course I'd like to know if the other terminal emulators have such a setting, but it is a setting & not a "patch," right? It would be good to know the latency of st with this setting all the way up, if you're willing :)

By "patch" i mean, a "modification to the source code". Since `st` adheres to the "suck less" philosophy, it does *not* support actual "settings", which I would define as a "runtime modification" which can be done without recompilation.

> Ah, so xterm would be below 3ms with dash, then? Cool.

I am not sure which numbers you're looking at, but both in the alacritty issue and the original article, xterm is, on average, below 3ms second. I didn't think it mattered to indicate which shell was running, because it was the same everywhere, but it was `bash` in all cases. Presumably dash would be as fast or faster.

I hope that answers your questions, and I encourage you to get familiar with the test suite and do those tests yourself, if you really want to dig deeper into this. I'm done with this project for now, and do not expect to rerun a full benchmark like this in the foreseeable future, other maybe than to bug alacritty again about their latency. ;)
